import type { ChainConfig } from "./types";

export const AVALANCHE_FUJI_CHAIN_ID = 43113;

const AVALANCHE_FUJI_RPC_URL =
  "https://twilight-small-rain.avalanche-testnet.quiknode.pro/ad1393483c2713058688a4e0fb47a308f29dd52d/ext/bc/C/rpc/";
const AVALANCHE_FUJI_RPC_FALLBACK_URL =
  "https://avalanche-fuji-c-chain-rpc.publicnode.com";

const AVALANCHE_FUJI_INBOX = "0xAb625bE229F603f6BBF964474AFf6d5487e364De";

/** Underlying ERC-20s from PrivacyPortalConfig.json (Avalanche Fuji). */
const MTT = "0x328e70e1c52662cd5f19f824fcb8b463d77a6686";
const USDC = "0x5425890298aed601595a70AB815c96711a31Bc65";
const WAVAX = "0xd00ae08403B9bbb9124bB305C09058E32C39A48c";

/** Deployed PoD portal pairs from pod-mpc-lib deployConfig.json (Fuji). */
const P_AVAX = "0x44392E67f6Fc5179BD25302519b1B85B87afc5D8";
const P_USDC = "0xAd40C2E98ef9d37827F5206D0a6641c29f2247c5";
const PORTAL_AVAX = "0xdf75091D4AF11b94FA318eeBC6CEBC106899E25C";
const PORTAL_USDC = "0x32146Ce8a96F2b0102c5C0f27e45E53eA30ef18B";

export const avalancheFujiChain: ChainConfig = {
  id: AVALANCHE_FUJI_CHAIN_ID,
  hexId: "0xa869",
  name: "Avalanche Fuji",
  rpcUrl: AVALANCHE_FUJI_RPC_URL,
  rpcFallbackUrls: [AVALANCHE_FUJI_RPC_FALLBACK_URL],
  explorerBaseUrl: "https://testnet.snowtrace.io",
  podInboxAddress: AVALANCHE_FUJI_INBOX,
  unlockStrategy: "manual-aes-key",
  portalStrategy: "pod-privacy-portal",
  addresses: {
    MTT,
    USDC,
    WAVAX,
    "p.MTT": "0xc1258E5C04A6933940105FE94cC9A4C2439d3402",
    "p.USDC": P_USDC,
    "p.AVAX": P_AVAX,
    PrivacyPortalMTT: "0x9a82B356c9f7F59aE2c04200358122eb99aE6364",
    PrivacyPortalUSDC: PORTAL_USDC,
    PrivacyPortalAVAX: PORTAL_AVAX,
  },
  tokens: [
    {
      symbol: "MTT",
      name: "MyTestToken",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: false,
      addressKey: "MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
    {
      symbol: "p.MTT",
      name: "Private MyTestToken",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
    {
      symbol: "USDC",
      name: "USD Coin",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: false,
      addressKey: "USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
    {
      symbol: "p.USDC",
      name: "Private USDC",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: true,
      addressKey: "p.USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
    {
      symbol: "AVAX",
      name: "Avalanche",
      icon: "/icons/avalanche.svg",
      decimals: 18,
      isPrivate: false,
      isNative: true,
      addressKey: "WAVAX",
      bridgeAddressKey: "PrivacyPortalAVAX",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
    {
      symbol: "p.AVAX",
      name: "Private WAVAX",
      icon: "/icons/avalanche.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.AVAX",
      bridgeAddressKey: "PrivacyPortalAVAX",
      supportedChainIds: [AVALANCHE_FUJI_CHAIN_ID],
    },
  ],
  walletNetwork: {
    chainId: "0xa869",
    chainName: "Avalanche Fuji Testnet",
    rpcUrls: [AVALANCHE_FUJI_RPC_URL, AVALANCHE_FUJI_RPC_FALLBACK_URL],
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    blockExplorerUrls: ["https://testnet.snowtrace.io"],
  },
  getBridgeDataOverride: addresses => [
    {
      bridgeName: "MTT PoD Portal",
      bridgeAddress: addresses.PrivacyPortalMTT,
      publicToken: "MTT",
      publicTokenIcon: "/icons/coti.svg",
      privateToken: "p.MTT",
      privateTokenIcon: "/icons/coti.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "USDC PoD Portal",
      bridgeAddress: addresses.PrivacyPortalUSDC,
      publicToken: "USDC",
      publicTokenIcon: "/icons/USDC.svg",
      privateToken: "p.USDC",
      privateTokenIcon: "/icons/USDC.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 6,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "AVAX PoD Portal",
      bridgeAddress: addresses.PrivacyPortalAVAX,
      publicToken: "AVAX",
      publicTokenIcon: "/icons/avalanche.svg",
      privateToken: "p.AVAX",
      privateTokenIcon: "/icons/avalanche.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
  ],
  indexPage: {
    showPodRequestTracker: true,
    amountModalGasLabel: "Estimated Gas and PoD fee",
    amountModalGasSymbol: "native",
  },
};
