import type { ChainConfig } from "./types";

export const AVALANCHE_C_CHAIN_ID = 43114;

const AVALANCHE_C_RPC_URL = "https://api.avax.network/ext/bc/C/rpc";

/** Canonical mainnet collateral — portal/pToken clones from pod-mpc-lib deployConfig.json after deploy. */
const USDC = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E";
const WAVAX = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7";

export const avalancheCChain: ChainConfig = {
  id: AVALANCHE_C_CHAIN_ID,
  hexId: "0xa86a",
  name: "Avalanche C-Chain",
  rpcUrl: AVALANCHE_C_RPC_URL,
  explorerBaseUrl: "https://snowscan.xyz",
  unlockStrategy: "manual-aes-key",
  portalStrategy: "pod-privacy-portal",
  addresses: {
    USDC,
    WAVAX,
    "p.USDC": "",
    "p.AVAX": "",
    PrivacyPortalUSDC: "",
    PrivacyPortalAVAX: "",
  },
  tokens: [
    {
      symbol: "USDC",
      name: "USD Coin",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: false,
      addressKey: "USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [AVALANCHE_C_CHAIN_ID],
    },
    {
      symbol: "p.USDC",
      name: "Private USDC",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: true,
      addressKey: "p.USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [AVALANCHE_C_CHAIN_ID],
    },
    {
      symbol: "AVAX",
      name: "Avalanche",
      icon: "/icons/avalanche.svg",
      decimals: 18,
      isPrivate: false,
      isNative: true,
      addressKey: "WAVAX",
      bridgeAddressKey: "PrivacyPortalAVAX",
      supportedChainIds: [AVALANCHE_C_CHAIN_ID],
    },
    {
      symbol: "p.AVAX",
      name: "Private WAVAX",
      icon: "/icons/avalanche.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.AVAX",
      bridgeAddressKey: "PrivacyPortalAVAX",
      supportedChainIds: [AVALANCHE_C_CHAIN_ID],
    },
  ],
  walletNetwork: {
    chainId: "0xa86a",
    chainName: "Avalanche C-Chain",
    rpcUrls: [AVALANCHE_C_RPC_URL],
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    blockExplorerUrls: ["https://snowscan.xyz"],
  },
  getBridgeDataOverride: addresses => [
    {
      bridgeName: "USDC PoD Portal",
      bridgeAddress: addresses.PrivacyPortalUSDC,
      publicToken: "USDC",
      publicTokenIcon: "/icons/USDC.svg",
      privateToken: "p.USDC",
      privateTokenIcon: "/icons/USDC.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 6,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "AVAX PoD Portal",
      bridgeAddress: addresses.PrivacyPortalAVAX,
      publicToken: "AVAX",
      publicTokenIcon: "/icons/avalanche.svg",
      privateToken: "p.AVAX",
      privateTokenIcon: "/icons/avalanche.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
  ],
  indexPage: {
    showPodRequestTracker: true,
    amountModalGasLabel: "Estimated Gas and PoD fee",
    amountModalGasSymbol: "native",
  },
};
