import type { ChainConfig } from "./types";

export const ETHEREUM_MAINNET_CHAIN_ID = 1;
const ETHEREUM_MAINNET_RPC = "https://eth.llamarpc.com";

/** Canonical mainnet collateral — portal/pToken clones from pod-mpc-lib deployConfig.json after deploy. */
const WETH = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";
const USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48";

export const ethereumMainnetPortalChain: ChainConfig = {
  id: ETHEREUM_MAINNET_CHAIN_ID,
  hexId: "0x1",
  name: "Ethereum Mainnet",
  rpcUrl: ETHEREUM_MAINNET_RPC,
  explorerBaseUrl: "https://etherscan.io",
  unlockStrategy: "manual-aes-key",
  portalStrategy: "pod-privacy-portal",
  addresses: {
    WETH,
    USDC,
    "p.USDC": "",
    "p.ETH": "",
    PrivacyPortalUSDC: "",
    PrivacyPortalETH: "",
  },
  tokens: [
    {
      symbol: "USDC",
      name: "USD Coin",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: false,
      addressKey: "USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [ETHEREUM_MAINNET_CHAIN_ID],
    },
    {
      symbol: "p.USDC",
      name: "Private USDC",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: true,
      addressKey: "p.USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [ETHEREUM_MAINNET_CHAIN_ID],
    },
    {
      symbol: "ETH",
      name: "Ether",
      icon: "/icons/wETH.svg",
      decimals: 18,
      isPrivate: false,
      isNative: true,
      addressKey: "WETH",
      bridgeAddressKey: "PrivacyPortalETH",
      supportedChainIds: [ETHEREUM_MAINNET_CHAIN_ID],
    },
    {
      symbol: "p.ETH",
      name: "Private WETH",
      icon: "/icons/wETH.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.ETH",
      bridgeAddressKey: "PrivacyPortalETH",
      supportedChainIds: [ETHEREUM_MAINNET_CHAIN_ID],
    },
  ],
  walletNetwork: {
    chainId: "0x1",
    chainName: "Ethereum Mainnet",
    rpcUrls: [ETHEREUM_MAINNET_RPC],
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    blockExplorerUrls: ["https://etherscan.io"],
  },
  getBridgeDataOverride: addresses => [
    {
      bridgeName: "USDC PoD Portal",
      bridgeAddress: addresses.PrivacyPortalUSDC,
      publicToken: "USDC",
      publicTokenIcon: "/icons/USDC.svg",
      privateToken: "p.USDC",
      privateTokenIcon: "/icons/USDC.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 6,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "ETH PoD Portal",
      bridgeAddress: addresses.PrivacyPortalETH,
      publicToken: "ETH",
      publicTokenIcon: "/icons/wETH.svg",
      privateToken: "p.ETH",
      privateTokenIcon: "/icons/wETH.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
  ],
  indexPage: {
    showPodRequestTracker: true,
    amountModalGasLabel: "Estimated Gas and PoD fee",
    amountModalGasSymbol: "native",
  },
};
