import type { ChainConfig } from "./types";

export const SEPOLIA_CHAIN_ID = 11155111;

export const sepoliaChain: ChainConfig = {
  id: SEPOLIA_CHAIN_ID,
  hexId: "0xaa36a7",
  name: "Sepolia",
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerBaseUrl: "https://sepolia.etherscan.io",
  unlockStrategy: "manual-aes-key",
  portalStrategy: "pod-privacy-portal",
  addresses: {
    MTT: "0xd3f5c63f4D87D2235b295FbA83351d31d0eD1BeE",
    "p.MTT": "0xb681D264a250715977450212d370b05d98761422",
    PrivacyPortalMTT: "0xF5Da19E1c8FB39Fdd11bB029882fc69E86650beB",
  },
  tokens: [
    {
      symbol: "MTT",
      name: "MTT",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: false,
      addressKey: "MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "p.MTT",
      name: "p.MTT",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
  ],
  walletNetwork: {
    chainId: "0xaa36a7",
    chainName: "Sepolia",
    rpcUrls: ["https://ethereum-sepolia-rpc.publicnode.com"],
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    blockExplorerUrls: ["https://sepolia.etherscan.io"],
  },
  getBridgeDataOverride: addresses => [{
    bridgeName: "MTT PoD Portal",
    bridgeAddress: addresses.PrivacyPortalMTT,
    publicToken: "MTT",
    publicTokenIcon: "/icons/coti.svg",
    privateToken: "p.MTT",
    privateTokenIcon: "/icons/coti.svg",
    depositFixedFee: "0",
    depositPercentageBps: "0",
    depositMaxFee: "0",
    withdrawFixedFee: "0",
    withdrawPercentageBps: "0",
    withdrawMaxFee: "0",
    minDepositAmount: "0",
    maxDepositAmount: "0",
    minWithdrawAmount: "0",
    maxWithdrawAmount: "0",
    accumulatedFees: "0",
    accumulatedCotiFees: "0",
    nativeCotiFee: "0",
    bridgeBalance: "0",
    isPaused: false,
    tokenDecimals: 18,
    isLoading: false,
    error: null,
  }],
  indexPage: {
    showPodRequestTracker: true,
    amountModalGasLabel: "Estimated Gas and PoD fee",
    amountModalGasSymbol: "native",
  },
};
