import type { ChainConfig } from "./types";

export const SEPOLIA_CHAIN_ID = 11155111;

/** Underlying ERC-20s from PrivacyPortalConfig.json (Sepolia). */
const WETH = "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9";
const USDC = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238";
const MTT = "0xd3f5c63f4D87D2235b295FbA83351d31d0eD1BeE";

/** Deployed PoD portal pairs from pod-mpc-lib deployConfig.json (Sepolia). */
const P_ETH = "0xDEA0e780134d15F51aC36B644F41d3dFD104E80A";
const P_USDC = "0x2749FE484a0E9555715e66638baF1e9a9e799E37";
const PORTAL_ETH = "0xfFbF6F92d51F8a0f86Cd367e9C7a974221dD38F2";
const PORTAL_USDC = "0xFA32bB6399cbC60A9A8d1535745dd063571a79Ed";

export const sepoliaChain: ChainConfig = {
  id: SEPOLIA_CHAIN_ID,
  hexId: "0xaa36a7",
  name: "Sepolia",
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerBaseUrl: "https://sepolia.etherscan.io",
  unlockStrategy: "manual-aes-key",
  portalStrategy: "pod-privacy-portal",
  podInboxAddress: "0xAb625bE229F603f6BBF964474AFf6d5487e364De",
  addresses: {
    MTT,
    WETH,
    USDC,
    "p.MTT": "0xb4AbD430486fBc50580354c10e3959BC7fE5E6e3",
    "p.USDC": P_USDC,
    "p.ETH": P_ETH,
    PrivacyPortalMTT: "0xDb71e6a73DA10Efc648C261E8B1f9d5babd25B08",
    PrivacyPortalUSDC: PORTAL_USDC,
    PrivacyPortalETH: PORTAL_ETH,
  },
  tokens: [
    {
      symbol: "MTT",
      name: "MyTestToken",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: false,
      addressKey: "MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "p.MTT",
      name: "Private MyTestToken",
      icon: "/icons/coti.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.MTT",
      bridgeAddressKey: "PrivacyPortalMTT",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "USDC",
      name: "USD Coin",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: false,
      addressKey: "USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "p.USDC",
      name: "Private USDC",
      icon: "/icons/USDC.svg",
      decimals: 6,
      isPrivate: true,
      addressKey: "p.USDC",
      bridgeAddressKey: "PrivacyPortalUSDC",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "ETH",
      name: "Ether",
      icon: "/icons/wETH.svg",
      decimals: 18,
      isPrivate: false,
      isNative: true,
      addressKey: "WETH",
      bridgeAddressKey: "PrivacyPortalETH",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
    {
      symbol: "p.ETH",
      name: "Private WETH",
      icon: "/icons/wETH.svg",
      decimals: 18,
      isPrivate: true,
      addressKey: "p.ETH",
      bridgeAddressKey: "PrivacyPortalETH",
      supportedChainIds: [SEPOLIA_CHAIN_ID],
    },
  ],
  walletNetwork: {
    chainId: "0xaa36a7",
    chainName: "Sepolia",
    rpcUrls: ["https://ethereum-sepolia-rpc.publicnode.com"],
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    blockExplorerUrls: ["https://sepolia.etherscan.io"],
  },
  getBridgeDataOverride: addresses => [
    {
      bridgeName: "MTT PoD Portal",
      bridgeAddress: addresses.PrivacyPortalMTT,
      publicToken: "MTT",
      publicTokenIcon: "/icons/coti.svg",
      privateToken: "p.MTT",
      privateTokenIcon: "/icons/coti.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "USDC PoD Portal",
      bridgeAddress: addresses.PrivacyPortalUSDC,
      publicToken: "USDC",
      publicTokenIcon: "/icons/USDC.svg",
      privateToken: "p.USDC",
      privateTokenIcon: "/icons/USDC.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 6,
      isLoading: false,
      error: null,
    },
    {
      bridgeName: "ETH PoD Portal",
      bridgeAddress: addresses.PrivacyPortalETH,
      publicToken: "ETH",
      publicTokenIcon: "/icons/wETH.svg",
      privateToken: "p.ETH",
      privateTokenIcon: "/icons/wETH.svg",
      depositFixedFee: "0",
      depositPercentageBps: "0",
      depositMaxFee: "0",
      withdrawFixedFee: "0",
      withdrawPercentageBps: "0",
      withdrawMaxFee: "0",
      minDepositAmount: "0",
      maxDepositAmount: "0",
      minWithdrawAmount: "0",
      maxWithdrawAmount: "0",
      accumulatedFees: "0",
      accumulatedCotiFees: "0",
      nativeCotiFee: "0",
      bridgeBalance: "0",
      isPaused: false,
      tokenDecimals: 18,
      isLoading: false,
      error: null,
    },
  ],
  indexPage: {
    showPodRequestTracker: true,
    amountModalGasLabel: "Estimated Gas and PoD fee",
    amountModalGasSymbol: "native",
  },
};
